spring.application.name=biblioteca-api

spring.datasource.url=jdbc:mysql://localhost:3306/biblioteca
spring.datasource.username=root
spring.datasource.password=aral@2
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


